### ISSUE TITLE
能不能加一个登录功能呢

### ISSUE THREAD

**Issue by EvanCsw** [softwaiter/markdown-website#1]
只是为了方便自己看文档的需求

**Comment by softwaiter** [comment]
你好，本项目创建的初衷就是方便个人或团队公开分享自己的md文档，所以做成了一个只包含前端页面的项目；如果需要增加登录必须增加后端接口开发，以及对某些资源进行权限控制，有一定的复杂度；当然，如果你对权限没有要求，可以只在前端页面增加一个登录界面，登录后跳转路由到内容页，唬弄唬弄外行也是可以的：)
