### ISSUE TITLE
3级菜单点击事件会报错

### ISSUE THREAD

**Issue by EvanCsw** [softwaiter/markdown-website#2]
{
    "title": "markdown-website",
    "topicWidth": 250,
    "openLevel": 3,
    "topics": [
        {
            "id": "01",
            "name": "markdown-website是什么？",
            "src": "/static/what.md"
        },
        {
            "id": "02",
            "name": "开始使用",
            "submenus": [
                {
                    "id": "0201",
                    "name": "搭建markdown网站",
                    "src": "/static/how.md"
                },
                {
                    "id": "0202",
                    "name": "更多网站属性配置",
                    "src": "/static/edit.md"
                }
            ]
        },
        {
            "id": "03",
            "name": "第二层菜单",
            "submenus": [
                {
                    "id": "0301",
                    "name": "第三层菜单",
                    "submenus": [
                        {
                            "id": "030101",
                            "name": "Docker学习笔记2",
                            "src": "/static/Docker学习笔记.md"
                        },
                        {
                            "id": "030102",
                            "name": "Docker学习笔记2",
                            "src": "/static/Docker学习笔记.md"
                        }
                    ]
                },
                {
                    "id": "0302",
                    "name": "部署发布",
                    "src": "/static/deploy.md"
                },
                {
                    "id": "0303",
                    "name": "hadoop单机安装",
                    "src": "/static/hadoop单机安装.md"
                },
                {
                    "id": "0304",
                    "name": "Hive Jdbc连接教程",
                    "src": "/static/Hive Jdbc连接教程.md"
                }
            ]
        }
    ]
}

**Comment by softwaiter** [comment]
已解决，请更新，多谢！

**Comment by EvanCsw** [comment]
> 已解决，请更新，多谢！

谢谢，已经解决了。要是能够根据文件夹和文件自动加载目录树，就很完美了。

**Comment by softwaiter** [comment]
> > 已解决，请更新，多谢！
> 
> 谢谢，已经解决了。要是能够根据文件夹和文件自动加载目录树，就很完美了。

是的， 这种实现会提升开发过程的友好性，但存在一个同样的问题，就是需要引入后端接口的支持，这个都超出了项目之初的想法：)

**Comment by 3030373635** [comment]
> > 已解决，请更新，多谢！
> 
> 谢谢，已经解决了。要是能够根据文件夹和文件自动加载目录树，就很完美了。

我就正在找这种项目。。。
